import React from "react";
import AccordionFAQ from "../../common/AccordionFAQ";

export default function WMDFAQ() {
  const faqs = [
    {
      question: "What is a workshop management dashboard software?",
      answer: "A workshop management dashboard software is a centralized digital analytics platform for garage and auto repair shop owners. It aggregates live job cards, daily revenue collections, mechanic performance, spare parts stock levels, and customer credit balances onto a single real-time screen."
    },
    {
      question: "How does the garage owner dashboard help track revenue and profits?",
      answer: "The garage owner dashboard automatically calculates daily cash, UPI, and card payments logged through invoices and counter sales. It tracks gross margins and highlights unpaid customer balances so you never lose revenue."
    },
    {
      question: "Is the workshop analytics dashboard updated in real-time?",
      answer: "Yes! Every time a service advisor opens a job card, a mechanic updates a repair stage on the Android mobile app, or a spare part is sold, the central dashboard updates immediately without requiring manual refresh."
    },
    {
      question: "Can I monitor mechanic performance on the mechanic dashboard software?",
      answer: "Absolutely. The mechanic dashboard view shows active job card assignments, repair completion speed, and total labor revenue generated by each technician, giving workshop owners full productivity insights."
    },
    {
      question: "Does the dashboard support multi-branch garage operations?",
      answer: "Yes. For multi-branch workshop owners, GarageSaarthi provides a master multi-branch dashboard that compares revenue, active job cards, and customer retention metrics across all your locations in one view."
    },
    {
      question: "Can I access the garage dashboard software on my smartphone?",
      answer: "Yes! GarageSaarthi is cloud-based and accessible from any Web browser, Tablet, or our dedicated Android Mobile App, allowing you to monitor your garage business while away from the shop."
    }
  ];

  return (
    <AccordionFAQ
      title="Workshop Management Dashboard"
      titleHighlight="FAQs"
      subtitle="Got questions about implementing a digital garage management dashboard for your auto repair business? We've got answers."
      faqs={faqs}
    />
  );
}
