name: Deploy to Production VPS
 
on:
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Deploy to PROD Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/garage/garage-landing
            git fetch origin
            git reset --hard origin/main
            git clean -fd
            npm install
            CI=true npm run build
            sudo systemctl reload nginx