name: Deploy to DEV VPS

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to DEV Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USER }}
          key: ${{ secrets.DEV_SSH_KEY }}
          script: |
            export PATH="$HOME/.local/share/pnpm:$PATH"
            cd /var/www/garage-saarthi/garage_saarthi_LP
            git fetch origin
            git reset --hard origin/development
            git clean -fd
            pnpm install
            CI=true pnpm build
            sudo systemctl reload nginx
